### ISSUE TITLE
how to run a NON-tls relay?  

### ISSUE THREAD

**Issue by realtebo** [codefresh-io/nat-traversal#2]
I need a short-live (1 hour max) relay for a demo.

I do not understand how to handle all TLS related stuff, so I'd like to simply start from a NON-TLS connections from relay server and relay client

how ?

**Comment by realtebo** [comment]
Opening the code I see how is the option "relayTls"  handled.

so i now use `--relayTls 0` on both sides and all works.

I want to thank you for developing this precious package!

**Comment by advance512** [comment]
@realtebo Thanks for the comment. You're welcome.
PRs are appreciated. :)
