### ISSUE TITLE
How to get Public IP for P2P service with clients that are behind NAT

### ISSUE THREAD

**Issue by techwizardg** [codefresh-io/nat-traversal#3]
We have a P2P App that works fine in local network but when they are behind NAT firewalls,they do not work as they do not have Public IP and i was thinking of using some service like Twilio to get NAT traversal done and they relay the Public IP Port to the other peer to work and can the same be achieved by using the relay and connect to some external TURN/ICE Server?Any help on the same would be appreciated

**Comment by advance512** [comment]
If you still haven't solved this, let me know, and I'll help. (9 days have gone by.)
Otherwise, please close this. :)
