### ISSUE TITLE
Describe the technique or techniques used

### ISSUE THREAD

**Issue by fresheneesz** [codefresh-io/nat-traversal#5]
Could you please describe which technique(s) this package uses to do nat traversal, in the readme? Also, a summary of the situations that/those technique(s) work and don't work in would be extremely useful in evaluating whether or not to use this package. Without knowing what techniques are used, its impossible to know if this package will work for what someone's trying to do.

**Comment by advance512** [comment]
A relay client runs on the target machine and makes an outgoing connection to the relay server.
The relay server will listen for incoming connections from the relay client. It also will listen for incoming connections from the main client.

When the main client connects to the relay server, the connection is tunneled all the way to the relay client, which then opens a connection to the main server and extends the tunnel. Thus, you have a tunnel from the main client to the main server.

The connection can be TLS encrypted, and a pre-shared secret key can be used to authorize relay clients (to prevent fake clients).

More info can be read at the README.

**Comment by fresheneesz** [comment]
It sounds like you've described hole punching. Is that the only technique used? The readme doesn't adequately describe this technique and doesn't mention that this is the only technique used. Please reopen this ticket until the readme adequately documents this.

**Comment by advance512** [comment]
I updated the README.

**Comment by leopucci** [comment]
> It sounds like you've described hole punching. Is that the only technique used? The readme doesn't adequately describe this technique and doesn't mention that this is the only technique used. Please reopen this ticket until the readme adequately documents this.

@fresheneesz This seems to be a relay only, have you found some other option ? with STUN or hole punch?
